### ISSUE TITLE
Implement an MVP of the Elasticsearch output

### ISSUE THREAD

**Issue by cmacknz** [elastic/elastic-agent-shipper#10]
Once https://github.com/elastic/elastic-agent-shipper/issues/7 is complete, implement basic support for the Elasticsearch output. 

The simplest solution is to use the existing beats Elasticsearch output, but we should evaluate the effort required to switch to the official go-elasticsearch client (https://github.com/elastic/elastic-agent-shipper/issues/14) with the initial output. If the effort is too high then switching the underlying Elasticsearch client can be deferred into a future iteration.

This feature is considered complete when at least the following criteria are satisfied:
- A test exists proving that an Elasticsearch output can be configured, and data published to the shipper is written to Elasticsearch.

**Comment by nimarezainia** [comment]
@cmacknz @jlind23 will this be targeted for 8.4?

**Comment by jlind23** [comment]
@nimarezainia this is something we may need for 8.3 in order to have the shippers properly working with an output.

**Comment by cmacknz** [comment]
I targeted it to 8.4. We might start it sooner though if we need it as Julien noted.

**Comment by jlind23** [comment]
@faec any update here?

**Comment by cmacknz** [comment]
Let's rescope this to just producing an MVP Elasticsearch output that allows a Beat to publish events through the shipper to a single datastream index. We will create follow up issues for the remaining features.

In the initial version we can assume the Elasticsearch output in the agent policy is trivial, like the basic example from https://www.elastic.co/guide/en/fleet/current/elasticsearch-output.html

```yaml
outputs:
  default:
    type: elasticsearch
    hosts: [127.0.0.1:9200]
    username: elastic
    password: changeme
```
