### ISSUE TITLE
Embed version information into the shipper.

### ISSUE THREAD

**Issue by cmacknz** [elastic/elastic-agent-shipper#113]
The shipper currently does not embed any version information. Before the first release, we need to incorporate the version information into the binary. This can be done using the agent's [version/version.go](version/version.go) and related code as a template.

The release automation should also be updated to automatically create a PR to bump main to the next minor version (or existing minor branch to the next patch version) when run.

**Comment by michalpristas** [comment]
automation already in place

**Comment by michalpristas** [comment]
closing PR went in
