### ISSUE TITLE
Include the shipper in the Elastic Agent diagnostic bundle

### ISSUE THREAD

**Issue by cmacknz** [elastic/elastic-agent-shipper#12]
The shipper state should be captured by the Elastic agent diagnostic command, documented here: https://www.elastic.co/guide/en/fleet/current/fleet-troubleshooting.html#_collect_elastic_agent_diagnostics_bundle

The diagnostic archive collects the following information:

- Elastic Agent versions numbers
- Beats (and other process) version numbers and process metadata
- Local configuration, elastic-agent policy, and the configuration that is rendered and passed to Beats and other processes
- Elastic Agent’s local log files

The diagnostics command is also able to collect pprof data in the archive if the `--pprof` flag is passed.

Ensure that the diagnostic command captures all the expected information when run, and add tests to ensure we do not break compatibility with the diagnostic command in the future.

**Comment by cmacknz** [comment]
Bringing into v8.4, hopefully this just works with minimal changes to the shipper. There may be some work to make the profile collection work.

**Comment by fearful-symmetry** [comment]
brief update, just to track this. On the agent, the command runs this: https://github.com/elastic/elastic-agent/blob/86ea452716a6299e3d877bb73c8a2d8a8deb5805/internal/pkg/agent/control/server/server.go#L239

Which reaches out to a unix socket and reads the pprof data. On the beat end, it just forwards the default HTTP pprof handler (I think) to a custom API endpoint in `./libbeat/api/routes.go` depending on if `pprof` is enabled in the beats config.

I'm guessing that something in agent sends the config to enable `pprof` and then reaches out via that unix socket when you run the `collect` command. We'll probably need to copy/import the server setup in `routes.go` or...something like that.

**Comment by fearful-symmetry** [comment]
Yep, this was deprioritized after the Beats/V2 work started. The main PR is in a steady state, so returning to this.

**Comment by cmacknz** [comment]
Updating to the version of the agent control client that includes https://github.com/elastic/elastic-agent-client/pull/3 should take care of this for us.
