### ISSUE TITLE
Build Tool to performance test shipper with & without disk queue

### ISSUE THREAD

**Issue by leehinman** [elastic/elastic-agent-shipper#124]
Relates #elastic/elastic-agent-inputs/#27
Relates #elastic/elastic-agent-inputs/#34
Relates #57

**Comment by cmacknz** [comment]
Do we want to attempt to do this via https://github.com/elastic/elastic-agent-shipper/issues/57? Or did you intend this to work differently, like a local command line benchmark of the shipper in isolation?

**Comment by leehinman** [comment]
> Do we want to attempt to do this via #57? Or did you intend this to work differently, like a local command line benchmark of the shipper in isolation?

I think within #57, I'd prefer there to be only way to perf test.

**Comment by cmacknz** [comment]
Closing in favour of https://github.com/elastic/elastic-agent-shipper/issues/57
