### ISSUE TITLE
Implement the Logstash output

### ISSUE THREAD

**Issue by cmacknz** [elastic/elastic-agent-shipper#129]
The same as https://github.com/elastic/elastic-agent-shipper/issues/10 and https://github.com/elastic/elastic-agent-shipper/issues/116, but for Logstash.

The agent supports a Logstash output today, so the shipper must implement a Logstash output to maintain feature parity with the outputs already available today.

*Acceptance Criteria*
* An integration test exists proving that the shipper can communicate with Logstash.
* An end to end test exists proving the agent can configure the shipper to communicate with Logstash.
* At least manual performance testing of the Logstash output has been performed.

**Comment by jlind23** [comment]
@leehinman any PR to provide here? Saw you made some progress on your fork?
