### ISSUE TITLE
`mage lint` is undefined

### ISSUE THREAD

**Issue by faec** [elastic/elastic-agent-shipper#141]
The repository `README` lists `mage lint` as the command to run the linter, but no such mage command exists.

**Comment by cmacknz** [comment]
Looks like the `lint` alias was removed accidentally in https://github.com/elastic/elastic-agent-shipper/pull/73/files#diff-520109d035a196d29d0a86e9c4e6c98e98abf056141b84df68c0d48167b87b25

**Comment by cmacknz** [comment]
Fix https://github.com/elastic/elastic-agent-shipper/pull/144
