### ISSUE TITLE
Implement `occupied_idle` metrics for the shipper

### ISSUE THREAD

**Issue by fearful-symmetry** [elastic/elastic-agent-shipper#142]
As part of https://github.com/elastic/elastic-agent-shipper/issues/11, we need an `occupied_idle` metric that reports events that have been ack'ed by the output, but are still occupied by the queue. This is part of a series of metrics first proposed by @faec here: https://github.com/elastic/beats/issues/31113#issuecomment-1128048645

Still looking into how to implement this, since it's been months since I've looked at the queue code, but I assume we might need to add something to `processACK` to track acked events, then subtract that from queue length.

CC @cmacknz

**Comment by cmacknz** [comment]
Closing, deferred until we have a concrete need for this metric. Let's focus on output metrics.
