### ISSUE TITLE
Allow configuring the Elasticsearch output's flush and worker parameters

### ISSUE THREAD

**Issue by cmacknz** [elastic/elastic-agent-shipper#149]
After switching to the go-elasticsearch client (https://github.com/elastic/elastic-agent-shipper/issues/14) we need to allow the user to configure at least the following parameters:

1. `FlushBytes`, which per https://github.com/elastic/elastic-agent-shipper/issues/28 we should name `maximum_batch_bytes` in our configuration.
2. `FlushInterval`, which per https://github.com/elastic/elastic-agent-shipper/issues/28 we should name `output_queue_flush_timeout` in our configuration.
3. `NumWorkers`, which we should likely map to the existing [worker](https://www.elastic.co/guide/en/beats/filebeat/current/elasticsearch-output.html#_worker) parameter for backwards compatibility reasons as long as we are convinced it works the same way to increase or decrease request concurrency. The BulkIndexer has a NumWorkers parameter that controls the number of concurrent requests that can be made at once, but it is not clear if it also bounds the number of connections that can be made to Elasticsearch. We should look at the underlying Elastictransport [metrics](https://pkg.go.dev/github.com/elastic/elastic-transport-go/v8/elastictransport#Metrics) to confirm the number of connections is what we expect.

The outcome of this issue should be an updated shipper configuration file that can be parsed and used to configure the go-elasticsearch BulkIndexer appropriately. The concurrency model of the go-elasticsearch BulkIndexer should also be clarified as part of this work, to confirm whether we can move forward with a single `worker` configuration or if we need to separate the worker configuration from the number of connections.

**Comment by cmacknz** [comment]
I provided a preliminary specification for some of these parameters to the Fleet UI team to unblock UI developmenet: https://github.com/elastic/kibana/issues/141508#issuecomment-1307665963

If we decide to implement these configurations in a different way we will need to follow up and ensure those changes are reflected in Fleet.

**Comment by jlind23** [comment]
Closing thanks to https://github.com/elastic/elastic-agent-shipper/pull/227
