### ISSUE TITLE
Add an integration test for the Kafka output

### ISSUE THREAD

**Issue by robbavey** [elastic/elastic-agent-shipper#166]
Add a basic integration test for the shipper Kafka output. The test should:

- Start Kafka as a Docker container.
- Start the shipper binary with a Kafka output configured to write to the Kafka Docker container.
- Setup topics as the target for the events that will be ingested during the test.
- Publish events to the shipper via the gRPC API and ensure they are ingested into the target topics with the expected format.

**Comment by cmacknz** [comment]
Relates to https://github.com/elastic/elastic-agent-shipper/issues/148, the test setup between the two is likely to be extremely similar.
