### ISSUE TITLE
The shipper should report its output unit as DEGRADED when it cannot publish events to Elasticsearch

### ISSUE THREAD

**Issue by cmacknz** [elastic/elastic-agent-shipper#174]
The shipper output unit should be reported as DEGRADED using the V2 control protocol when it cannot connect or write to Elasticsearch.

We should not report the status as DEGRADED on the first error, but only when the condition has persisted after several retries. Initially we can consider only setting the status to DEGRADED if the problem persists for 30 seconds.

We should additionally consider setting the status as FAILED if we believe the error is not recoverable, for example because the TLS configuration is incorrect.

**Comment by fearful-symmetry** [comment]
Should we make that 30s variable configurable?

**Comment by cmacknz** [comment]
I don't see why not.
