### ISSUE TITLE
Support targeting multiple Elasticsearch indices

### ISSUE THREAD

**Issue by faec** [elastic/elastic-agent-shipper#202]
Currently the shipper can only output to a single Elasticsearch index. This is in part a constraint of our support library `go-elasticsearch`, whose BulkIndexer can only target one index (thus to target more than one would require multiple bulk indexers, each with their own workers and so on). In the long run, however, we need to be able to ingest to multiple indices from a single worker / memory pool.

Resolving this will likely involve collaborating with the `go-elasticsearch` maintainers to add multi-index support to the library, or to find a suitable workaround for our purposes if that is infeasible for some reason. (It's also possible that we've misunderstood the API and this is already possible with the current library; either way, coordinating with @Anaethelion will probably clarify things.)

**Comment by cmacknz** [comment]
As part of this we should upgrade to v8.6.0 of the Elasticsearch client to pick up the fix to https://github.com/elastic/go-elasticsearch/issues/557
