### ISSUE TITLE
[Elastic Agent Shipper] Modify the copy for Disk Queue configurtaion in shipper

### ISSUE THREAD

**Issue by nimarezainia** [elastic/elastic-agent-shipper#218]
Make the "encryption" option for Disk Queue in the new shipper a bit more explicit:

<img width="499" alt="image" src="https://user-images.githubusercontent.com/13442829/212787439-cabcb138-a1e0-48b7-90d5-985782754a89.png">

Changing "Encryption" to "Disk Queue Encryption"

(fyi @criamico @cmacknz )

**Comment by criamico** [comment]
@nimarezainia I added this change in the follow up ticket scheduled for the next sprint.

**Comment by amitkanfer** [comment]
@criamico does it mean we can close this one?

**Comment by jlind23** [comment]
Let's keep it open for now as it will be closed by: https://github.com/elastic/kibana/issues/147613

**Comment by jen-huang** [comment]
Closing this in favor of less duped issues. Updated https://github.com/elastic/kibana/issues/147613 to include exact change needed.
