### ISSUE TITLE
There should be a single Elastic Agent spec file for the shipper

### ISSUE THREAD

**Issue by cmacknz** [elastic/elastic-agent-shipper#222]
There are two spec files defined for the shipper, one in the shipper repository and one in the agent repository both with a different syntax:
* https://github.com/elastic/elastic-agent-shipper/blob/main/elastic-agent-shipper.spec.yml
* https://github.com/elastic/elastic-agent/blob/main/specs/shipper.spec.yml

Delete the unneeded spec file (ideally the one in the agent repository) and ensure the right syntax is used in the chosen spec file that is included with the build and packaged alongside the elastic-agent-shipper binary.

**Comment by cmacknz** [comment]
https://github.com/elastic/elastic-agent/pull/2130 made it so that the spec file packaged with the shipper will take precedence over the one in the agent repository. 

It also attempted to remove https://github.com/elastic/elastic-agent/blob/main/specs/shipper.spec.yml but it appears is is used in the agent tests and there will need to be some follow up work to remove it. This spec file is just `shipper` which does not match the binary name of `elastic-agent-shipper` and would not be used even if it was packaged with the agent.

**Comment by leehinman** [comment]
#254 does one in elastic-agent-shipper repository.  Will need to see if we can have tests in elastic-agent pull from this repo, can't just delete because tests break.
