### ISSUE TITLE
ES output marshalling entire gRPC object

### ISSUE THREAD

**Issue by fearful-symmetry** [elastic/elastic-agent-shipper#240]
Right now, the shipper is marshaling the entire gRPC object to JSON before sending it to ES, resulting in some mapping errors:
```
"Limit of mapping depth [20] has been exceeded due to object field [fields.data.system.Kind.StructValue.data.memory.Kind.StructValue.data.actual.Kind.StructValue.data.used.Kind.StructValue.data.bytes.Kind]
```
There's a TODO for this already in the ES output:
```
func serializeEvent(event *messages.Event) ([]byte, error) {
	// TODO: we need to preprocessing the raw protobuf to get fields in the
	// right place for ECS. This just translates the protobuf structure
	// directly to json.
	return json.Marshal(event)
}
```

**Comment by cmacknz** [comment]
We definitely need to fix this to be able to performance test this properly. 

@fearful-symmetry looks like everything you have in the sprint is in a PR already, so seems like you have the time to take on fixing this. I've assigned it to you in the current sprint CC @pierrehilbert

**Comment by cmacknz** [comment]
First thoughts, we do not want to serialize the entire event:

https://github.com/elastic/elastic-agent-shipper-client/blob/7610e1852122c0e441800549ab1121aded6e3a06/api/messages/publish.proto#L32-L42

```protobuf
message Event {
 // Creation timestamp of the event.
 google.protobuf.Timestamp timestamp = 1;
 // Source of the generated event.
 Source source = 2;
 // Data stream for the event.
 DataStream data_stream = 3;
 // Metadata JSON object (map[string]google.protobuf.Value)
 messages.Struct metadata = 4;
 // Field JSON object (map[string]google.protobuf.Value)
 messages.Struct fields = 5;
}
```

The `fields` struct should be the event as it was received from the input, output from Filebeat for example (unless the conversion to protobuf is modifying it that is).

My suspicion is we just want to serialize the `fields` Struct, possibly we should rename it to make it more obvious if this is the case. The fields should already include the timestamp, the `DataStream` fields which we extract into their own message here so we can easily determine the target index, and the `metadata` is obviously metadata we would not want to send to ES.

**Comment by fearful-symmetry** [comment]
Yah, the only reason I filed an issue instead of just chucking a fix into the shipper config PR was because I wasn't 100% sure how we wanted to handle that `Event` object.

**Comment by cmacknz** [comment]
As part of this work, it is worth comparing the event as output by Filebeat with the file or console output to the event output by the shipper ES output (or console output if we confirm or make the serialization the same). The events should be identical. The shipper should not be modifying the structure of events at all. Right now it should just be a proxy for the output.
