### ISSUE TITLE
Fix so shipper doesn't stall while sending via elasticsearch output

### ISSUE THREAD

**Issue by leehinman** [elastic/elastic-agent-shipper#255]
Noticed 3 times that shipper stopped sending data after ~150,000 events.  Filebeat showed it hadn't finished the file and would have sent more data.

**Comment by pierrehilbert** [comment]
@leehinman is this one still relevant or did the last fixes solve it?

**Comment by leehinman** [comment]
Sent 5 million events through the shipper, no issues.  Previously it would fail in under 100k.
