### ISSUE TITLE
Archive this repository and remove the elastic-agent-shipper binary from the release process

### ISSUE THREAD

**Issue by cmacknz** [elastic/elastic-agent-shipper#306]
If the prototype of the shipper as a Filebeat implementation succeeds in https://github.com/elastic/beats/issues/35135, then we will archive this repository and remove the elastic-agent-shipper binary from the elastic agent build and release process.

- [x] https://github.com/elastic/elastic-agent-shipper-client/pull/30 [Disable or delete all Jenkins jobs for the shipper: https://fleet-ci.elastic.co/job/elastic-agent-shipper-mbp/](https://github.com/elastic/infra/pull/39636)
- [x] Remove the shipper from the Elastic stack release process
- [x] Delete the shipper DRA bucket currently used in the stack release process
- [x] https://github.com/elastic/infra/pull/39636 Remove the shipper from the elastic agent build process: https://github.com/elastic/elastic-agent/blob/7506b3d89477c8643845c632b3820a9b55ca0e27/magefile.go#L780

**Comment by cmacknz** [comment]
The release engineer team has removed the shipper binary from the DRA and release process for 8.10. We still need to remove our own CI pipelines and remove it from our internal release automation.

**Comment by jlind23** [comment]
Closing this as done as everything was cleaned up
