### ISSUE TITLE
Setup the shipper's build, lint, and CI process

### ISSUE THREAD

**Issue by cmacknz** [elastic/elastic-agent-shipper#4]
Setup the shipper repository with the standard mage targets (check, build, unitTest, etc.). The mage and lint targets should match those setup for https://github.com/elastic/elastic-agent-libs and use the same golangci-lint configuration. The lint step in CI should use a Github action, see https://github.com/elastic/beats/pull/30985/files for the setup.

Jenkins should be configured to run the lint, build, and test steps on each supported platform. The output of the build should initially be an elastic-agent-shipper binary, which can start as an empty main.go file. The https://github.com/elastic/elastic-agent repository can be used as a reference for a build process that produces a binary artifact.

Automated Go version bumps should be configured: https://github.com/elastic/observability-robots/blob/main/docs/bump-versions.md#go-bump

The CI onboarding Jenkins job has already been run, resulting in the following PRs that should be reviewed and merged:

- https://github.com/elastic/elastic-agent-shipper/pull/1
- https://github.com/elastic/elastic-agent-shipper/pull/2

We should attempt to reuse the mage targets from the elastic agent where possible: https://github.com/elastic/elastic-agent/issues/321

**Comment by fearful-symmetry** [comment]
Now that the initial PR is merged, we have a basic CI and a handful of custom and imported mage targets.

The biggest issue is that a lot of the glue code we'd want to have in the shipper currently lives in the the elastic-agent repo in a non-importable form. I'm not a big fan of copy-and-pasting that much code, so we need to look into migrating a lot of those existing targets and helper code back into `elastic-agent-libs`

**Comment by fearful-symmetry** [comment]
I think we can close this? The shipper now has `notice` and all the other needed targets. There's still some rough edges, but I don't think we're actually missing anything?

**Comment by cmacknz** [comment]
I think we might be missing the automation to bump the Go version automatically: https://github.com/elastic/observability-robots/blob/main/docs/teams/ci/bump-versions.md#go-bump

Specifically https://github.com/elastic/apm-pipeline-library/blob/main/.ci/.bump-go-release-version.yml

We are missing that for a few of the new repositories it seems.

**Comment by fearful-symmetry** [comment]
Hah, I didn't even know that was a thing.

**Comment by fearful-symmetry** [comment]
@cmacknz alright, we have the automation for the version bump set up.
