### ISSUE TITLE
Allow running the shipper in standalone mode independently of the agent

### ISSUE THREAD

**Issue by cmacknz** [elastic/elastic-agent-shipper#83]
The shipper's default mode of operation is to expect to be started by the agent, expecting to be passed the address of the agent control protocol server to connect to. The control protocol is then responsible for sending the shipper it's runtime configuration.

To make local development and testing easier, allow the shipper to run in a standalone mode independent of the agent. Add a new command line flag that causes the shipper to read its configuration file from disk and start without waiting to connect to the agent control protocol server.

**Comment by rdner** [comment]
It's currently possible to run the shipper server using the controller mock like so:

https://github.com/elastic/elastic-agent-shipper/blob/34571c41e892f8498d817a3b2784cc372b0985a2/controller/controller_client_test.go#L34-L91

We're planning to automate this but for the time being it can be coded quickly for debugging.

**Comment by rdner** [comment]
For now it's going to be implemented as a flag that uses a configuration file bypassing the control protocol altogether. This will enable us to run integration tests without running the actual agent.

However, there is this [agent mock tool being developed](https://github.com/elastic/ingest-dev/issues/1198) that will allow us to include the control protocol implementation in our integration tests as well. The flag is rather a temporary solution.
