### ISSUE TITLE
Beats shipper output should not wait for full acknowledgment before sending more batches

### ISSUE THREAD

**Issue by faec** [elastic/elastic-agent-shipper#98]
The current draft of the Beats shipper output waits for full transmission and acknowledgment of every batch of events before it sends another. In particular, this means that no matter how big the shipper queue is, the Beats shipper output will never use more than one batch worth of it, and the overall throughput is limited -- similar to if a Beats input waited on full end-to-end acknowledgment in between each Publish call.

Instead, we need to send batches as they come in and handle acknowledgment asynchronously, so events accumulate in the shipper queue as intended.

A sketch of how this might be implemented, from a thread on the original PR (https://github.com/elastic/beats/pull/32708):

(1) add a list of pending batches to the shipper struct

```go
type shipper struct {
	...
	pending []struct {
		batch publisher.Batch
		index uint64
	}
	pendingLock sync.Mutex
}
```

(2) modify `shipper.Publish` so it sends _all_ events in the batch (making multiple upstream publish calls if necessary), and saves the batch as well as the _final_ accepted index in `shipper.pending`. [This is more in keeping with the intent of the API anyway: currently the shipper only blocks until at least one event is sent, but that's just because the queue is full, not because some of the events really "failed." So marking these events as failed and needing retry in the beats output doesn't fit the usual semantics -- we don't want to be potentially dropping lots of events over "repeated failures" when all that's really happening is back pressure.]

(3) Add a continuous listener to `PersistedIndex`, and when a new value comes in do something like:

```go
s.pendingLock.Lock()
batchCount := 0
while batchCount < len(s.pendingLock) && s.pending[batchCount].index < newPersistedIndex {
	s.pending[batchCount].ACK()
	batchCount++
}
s.pending = s.pending[batchCount:]
s.pendingLock.Unlock()
```

**Comment by rdner** [comment]
@faec I have some questions regarding (3):

1. What happens when we reconnect to another server while listening to `PersistedIndex` and when the next pending batch was sent to a previous server with a different UUID. In this case the `PersistedIndex` value will start over from 0, right? My idea was that we have to cancel the whole batch. This edge case is not mentioned in the issue description.
2. I see a memory leak in the pseudo-code here. The way slices are allocated we cannot trim them from the beginning and keep adding to the end without moving items, otherwise the underlying array will grow indefinitely. That's the reason I proposed to use a buffered channel earlier in https://github.com/elastic/beats/pull/32708#discussion_r949298073

**Comment by rdner** [comment]
For the 2., the simplest solution would be something like this: 

https://go.dev/play/p/NPZKIkVaDT4

```go
arr := []string{"one", "two", "three", "four", "five"}
trimIndex := 2
copy(arr[0:], arr[trimIndex:])
fmt.Println(arr) // [three four five four five]
arr = arr[trimIndex:]
fmt.Println(arr) // [five four five]
```

unless someone can suggest a better idea.

**Comment by faec** [comment]
1. Anytime the UUID changes we need to reset everything. This means cancelling all outstanding batches and restarting the PersistedIndex listener, both of which could be done in the connection callback (when connect is called it can check for and clean up any existing batches / listeners from a previous connection). The persisted index will start over from 0 in the shipper, although we aren't guaranteed to observe that since other clients may exist; we just need to start the listener back up and accept the new value.
2. Yes, technically as written there's a leak, and the array needs to be cleaned up periodically. I would recommend against a buffered channel -- (a) that requires an explicit fixed buffer size, and breaks when we exceed it, but in this context we have no particular reasonable upper bound on the number of outstanding batches, and (b) when we read a new PersistedIndex, we need to go through the outstanding batches checking which ones have been acknowledged. However, if we use a channel, then we can't do this in place -- we won't know if a particular batch should be acknowledged until after we remove it from the buffered channel, and if it turns out that one isn't done yet, then we want to put it back at the front of the queue. So I'd recommend something based on an array or similar helper object that can inspect things in-place. One simple workaround would be to follow the pseudocode but flush the array by creating a new copy every 1000 acknowledged batches (say), but anything that acts like a traversible ordered queue should work.

**Comment by rdner** [comment]
@faec I didn't push for the channel implementation in 2. at all, I just mentioned my reasons behind the previous approach I took.

What I actually propose in 2. requires moving all the array items to the left as I describe in https://github.com/elastic/elastic-agent-shipper/issues/98#issuecomment-1224186523 unless you have a more efficient idea how to do that.

Regarding 1. I think we're on the same page here.

All the code can be found in the PR here https://github.com/elastic/beats/pull/32785
